version: "3.8" # Specify docker-compose version

services:
  db:
    image: postgres:latest
    container_name: drawly_postgres_db
    restart: always
    environment:
      POSTGRES_DB: whiteboard_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
